# 配置Sharding-JDBC数据源名称，可配置多个
spring:
  shardingsphere:
    datasource:
      name: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://127.0.0.1:3306/dubhe-cloud-prod?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&useInformationSchema=true
        username: test
        password: test

    #指定data_dataset表 主键id 生成策略
    sharding:
      tables:
        data_file:
          actual-data-nodes: master.data_file_$->{1..250}
          table-strategy:
            standard:
              sharding-column: dataset_id
              precise-algorithm-class-name: org.dubhe.data.util.MyPreciseShardingAlgorithm

        data_dataset_version_file:
          actual-data-nodes: master.data_dataset_version_file_$->{1..250}
          table-strategy:
            standard:
              sharding-column: dataset_id
              precise-algorithm-class-name: org.dubhe.data.util.MyPreciseShardingAlgorithm

        data_file_annotation:
          actual-data-nodes: master.data_file_annotation_$->{1..250}
          table-strategy:
            standard:
              sharding-column: dataset_id
              precise-algorithm-class-name: org.dubhe.data.util.MyPreciseShardingAlgorithm
                    
      props:
        sql:
          show: true
management:
  health:
    db:
      enabled: false