spring:
  # serving预测上传文件大小限制
  servlet:
    multipart:
      # 设置单个文件的大小
      max-file-size: 10MB
      # 设置单次请求的文件的总大小
      max-request-size: 100MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#      routes:
#      - id: weight_high
#        uri: https://weighthigh.org
#        predicates:
#          - Weight=group1, 8
#      - id: weight_low
#        uri: https://weightlow.org
#        predicates:
#          - Weight=group1, 2
#      - id: my_route   #路由的ID，没有固定规则但要求唯一，建议配合服务名
#        uri: http://baidu.com #匹配后提供服务的路由地址
#        predicates:
#          - Path=/get         # 断言，路径相匹配的进行路由

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

serving:
  gateway:
    postfixUrl: .api.dubhe.ai
    token:
      secret-key: password
      expire-seconds: 108000
    http-port: "32493"
    corePoolSize: 10
  group: serving_test_group

#关闭熔断机制
feign:
  hystrix:
    enabled: false