#配置数据源
spring:
  redis:
    #数据库索引
    database: 1
    host: 10.5.26.88
    port: 6379
    password:
    #连接超时时间
    timeout: 5000
  # 配置允许后面的Bean覆盖前面名称重复的Bean
  main:
    allow-bean-definition-overriding: true